### ISSUE TITLE
Database ERD 설계

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#1]
MySQL을 사용하는 RDBMS형 ERD 설계

# draw.io
link : https://app.diagrams.net/#G1rGqkrOL-Q9D_B2iqUWrFqMo0A7cj7Ae8

# ERD cloud
link : https://www.erdcloud.com/d/ayC3YAqrkJPvqKzbJ

**Comment by Enble** [comment]
저 주소로 바로 들어가면 안보입니다.
https://drive.google.com/file/d/1rGqkrOL-Q9D_B2iqUWrFqMo0A7cj7Ae8/view

**Comment by minsang-alt** [comment]
확인했습니다.

**Comment by minsang-alt** [comment]
draw.io가 직접 그려야한다는 불편함이 있어 ERD Cloud로 옮기겠습니다 @Enble

**Comment by minsang-alt** [comment]
https://www.erdcloud.com/d/tSnipoe6gGo84z9yw

**Comment by Enble** [comment]
실수로 코멘트 안 달고 이슈 닫았네요...
확인했습니다!

**Comment by minsang-alt** [comment]
이슈는 다음 주차 회의할 때 검토하면서 이슈 close하는걸로 하죠!
