### ISSUE TITLE
재난 문자 (크롤링 학습)

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#11]
구현 방식 의논

**Comment by Enble** [comment]
서버 내에서 실시간, 혹은 준 실시간(10초 간격)으로 재난 문자 uri에서 content를 긁어올 수 있는 방식이어야 함.

**Comment by minsang-alt** [comment]
스프린트 3주차에 구현을 하기때문에 해당 이슈는 종료하겠습니다
