### ISSUE TITLE
프로젝트 기본 구조 생성

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#13]
## 프로젝트 생성
- gradle
- spring boot 3.1.2
- java 17

## gitignore 생성
- application-aws.properties 따로 공유 

## 패키지 구조 설정
- 계층형

## 의존성 설정 
 - lombok
 - spring web
 - jpa
 - mysql driver

**Comment by Enble** [comment]
확인했습니다.

**Comment by minsang-alt** [comment]
해당 이슈도 종료

**Comment by minsang-alt** [comment]
### MVC 패턴

![Image](https://github.com/Beacon-2023/Beacon-backend/assets/82764703/801552ad-1e2d-4c11-be7b-d987863fefa7)

출처 : https://velog.io/@ohzzi/Entity-DAO-DTO%EA%B0%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C

**Comment by minsang-alt** [comment]
프로젝트 구조 : 도메인 디렉터리 구조
