### ISSUE TITLE
핸들링할 재난 종류 정하기

### ISSUE THREAD

**Issue by Enble** [Beacon-2023/Beacon-backend#17]
앱에서 다룰 재난 종류를 확정해야 할 필요가 있습니다.

선정하는 기준을 다음과 같이 잡으면 좋을 것 같습니다.
- 우리나라에서 자주 발생하는 재난
- 관련 대피소가 명확하게 제시된 재난

**Comment by minsang-alt** [comment]
재난은
- 민방위(민방위대피소이용),
- 산불,태풍,호우,대설(이재민 임시 주거시설 대피소 이용)
- 지진(지진옥외대피장소 대피소 이용)

**Comment by Enble** [comment]
수정
* 민방위
* 산불
* 태풍
* 홍수
* 지진
* 그 외(etc)
