### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#25]
- aws 서버 띄우기(백엔드) 👍 
- 대피소 확인해서 재난 코드 결정 👍
- swagger를 통한 api 통합 테스트 (프론트)

- workmanger를 서버 넘기기 (프론트,백엔드)
- 법정동 코드 및 추가적인 데이터를 mysql에 테이블 저장 (백엔드)

- FCM 서버구축 (푸시알람) (백엔드, 프론트)
- 언어 구축(프론트)

**Comment by Enble** [comment]
이슈 닫습니다.
