### ISSUE TITLE
대피소 정리

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#27]
1. 지진 옥외 대피소
https://www.safekorea.go.kr/idsiSFK/neo/sfk/cs/sfc/res/victimList.jsp?acmdfclty_cd=2&emgPage=Y&menuSeq=855
2. 민방위 대피소

[민방위대피시설.csv](https://github.com/Beacon-2023/Beacon-backend/files/12343021/default.csv)

3. 이재민 임시 주거 시설 대피소
https://www.safekorea.go.kr/idsiSFK/neo/sfk/cs/sfc/res/acmdfcltyList.jsp?emgPage=Y&menuSeq=859

**Comment by minsang-alt** [comment]
이재민임시주거시설 csv로 변환 완료

**Comment by minsang-alt** [comment]
지진 옥외 대피장소 csv변환 완료

**Comment by Enble** [comment]
확인했습니다.
