### ISSUE TITLE
테스트 실행 불가

### ISSUE THREAD

**Issue by Enble** [Beacon-2023/Beacon-backend#28]
@minsang-alt 
현재 *일부 테스트 실행이 안됩니다. 아마 interceptor 부분에서 문제가 생긴 것 같은데 확인 부탁드립니다.

**Comment by minsang-alt** [comment]
어떤 오류인지 알아야 할것 같습니다

**Comment by minsang-alt** [comment]
실행해보니 10개중 7개 통과했는데 다 실패인건가요?

**Comment by Enble** [comment]
수정 되었으므로 이슈 닫겠습니다.
