### ISSUE TITLE
Member 컨트롤러에서 Entity 취급 문제

### ISSUE THREAD

**Issue by Enble** [Beacon-2023/Beacon-backend#34]
#21 현재 Member 컨트롤러에서 Member Entity를 Service단에서 직접 받아와서 사용하고 있습니다.
따라서 저는 Service에서 dto를 통해 Controller에서는 Entity를 직접 취급하지 않도록 하는 것이 좋아 보입니다.
민상님은 어떻게 생각하시나요?

**Comment by minsang-alt** [comment]
아 저 그거 수정하려고 남겨두고 있었습니다 빠른 시일내에 수정하도록 하겠습니다 👍

**Comment by minsang-alt** [comment]
해당 이슈는 해결되었으므로 closed하겠습니다
