### ISSUE TITLE
재난 OPEN API => 국민재난안전포털 스크래핑으로 변경

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#4]
- 현재 OPEN API 중 하나인 https://www.data.go.kr/data/3058822/openapi.do 를 이용하려 했지만 하루 4번 업데이트 

- 다음 블로그에 따르면 https://earningbirds.netlify.app/development/firebase%EC%99%80-aws-lambda%EB%A1%9C-%EC%9E%AC%EB%82%9C%EB%AC%B8%EC%9E%90-%EC%8A%A4%ED%81%AC%EB%9E%98%ED%95%91%ED%95%98%EA%B8%B0/

국민재난안전포털이 실시간으로 업데이트 
https://www.safekorea.go.kr/idsiSFK/neo/sfk/cs/sfc/dis/disasterMsgList.jsp?menuSeq=679

**Comment by Enble** [comment]
확인했습니다.
