### ISSUE TITLE
법정동 csv 파일 교체

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#41]
좌표를 통해 카카오 api요청을 하면 
(
참고 : 
https://developers.kakao.com/docs/latest/ko/local/dev-guide#coord-to-district-sample
)

이렇게 

![Image](https://github.com/Beacon-2023/Beacon-backend/assets/82764703/58b0c02a-da2a-42cd-9a47-f945fd468698)

법정동 코드를 출력할 수 있습니다.

하지만 지금쓰는 법정동 코드가 현재 최신화되있지 않아서 새로운 법정동 코드를 써야 합니다

https://blog.naver.com/s9soft/221658209696

여기에 있는 법정동 csv파일을 이용하고 싶은데 혹시 생기는 이슈가 있을까요? 여기 csv파일에는 법정동 코드만 있고 지역코드는 없는 상태입니다

**Comment by Enble** [comment]
@minsang-alt 이거 법정동 코드가 변경된거면 매핑하기가 까다롭겠는데요?

**Comment by Enble** [comment]
그리고 제가 블로그 확인해봤는데 딱히 법정동 코드에 변화가 있는거 같지는 않긴 한데... 1대1 대조를 해본건 아니라서 약간 애매하네요

**Comment by minsang-alt** [comment]
기존꺼는 아마도 읍면까지만 있습니다 리는 포함되지 않았고요 방법을 강구해야할 것 같습니다.. 
@Enble

**Comment by Enble** [comment]
정상작동 확인되어 이슈 닫습니다.
