### ISSUE TITLE
법정동코드를 통해 지역코드 찾기 기능 추가

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#42]
#41 에서도 언급했지만 api를 통해 법정동 코드를 얻기때문에 지역코드로 변환해야하는 작업이 필요하므로 기능 추가 해주시면 될것 같습니다

**Comment by Enble** [comment]
이미 있는 기능으로 구현 가능합니다.

**Comment by Enble** [comment]
이슈 닫습니다.
