### ISSUE TITLE
FcmTokenService에서 username 관련

### ISSUE THREAD

**Issue by Enble** [Beacon-2023/Beacon-backend#54]
프론트에서 FcmTokenController의 tokenRegister로 요청할 때, username과 함께 보내는 것으로 설계되어 있습니다.
이 부분에서 프론트에서 username을 null로 보낼 수는 없고 username을 빈 문자열("")로 보낸다고 합니다. 이 부분 확인하셔서 FcmTokenService 에서 null 체크가 아니라 empty 체크 하시면 될 것 같습니다.

**Comment by minsang-alt** [comment]
수정됨으로 이슈는 닫겠습니다
