### ISSUE TITLE
Git Commit Convention

### ISSUE THREAD

**Issue by minsang-alt** [Beacon-2023/Beacon-backend#7]
# 깃 컨밴션 작성 

참고 문헌 : 
https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

**Comment by minsang-alt** [comment]
@Enble 
커밋 컨밴션을 Subject랑 Body만 작성하는 걸로 할까요? footer까지 지키면 기회비용면 에서 손해일거 같습니다

**Comment by minsang-alt** [comment]
@Boknami 프론트는 혼자 작업 하시지만 검토해보고 괜찮다 싶으면 커밋 컨밴션 따르는 것도 좋을 듯 합니다

**Comment by Enble** [comment]
@minsang-alt 글에서도 footer는 옵셔널하다고 했으니까 필요하면 적고, 필요없으면 굳이 안적어도 될 것 같습니다.

**Comment by minsang-alt** [comment]
해당 이슈는 종료하겠습니다

**Comment by Boknami** [comment]
프론트도 해당 내용을 참고해서 진행하겠습니다.
